### ISSUE TITLE
New files created by emacs don't get synced until after restarting emacs.

### ISSUE THREAD

**Issue by jistanidiot** [Floobits/floobits-emacs#22]
To reproduce the problem:
Connect to a workspace.  
Do stuff )or not)
Create a new file

The new file will not be visible to anyone else until after you shutdown emacs and reconnect to the workspace.

I'm using emacs 23.4.1 on Kubuntu 12.10

**Comment by Kungi** [comment]
Im am having this problem with the current version from melpa (Version 23). Can someone confirm this?

**Comment by kans** [comment]
@Kungi 
What happens if you save the file (as a child of the root directory)?

**Comment by Kungi** [comment]
@kans 
Nothing happens.

More precisely.
I have a directory floobits-test which I use as my root for M-x floobits-join-workspace.
Then I create a new file like  floobits-test/does-it-upload.clj fill some text in and save it in emacs.
Then nothing happens.

**Comment by ggreer** [comment]
Do you see anything suspicous in *Messages* or *Floobits* after saving? Also, you may want to try using Emacs 24. We haven't tested on 23 in a while, and I bet we use some features that are only in 24.

Oh, and if you want to get more verbose logging, you can add `"debug": true` to your `~/.floorc.json`. Be warned: It can be annoyingly verbose.
