### ISSUE TITLE
MELPA install fails, "Package `json-1.2' is unavailable"

### ISSUE THREAD

**Issue by terotil** [Floobits/floobits-emacs#33]
This is "GNU Emacs 23.4.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.10) of 2012-09-08 on trouble, modified by Debian" and I did

    M-x package-refresh-contents <RET>
    M-x package-install <RET> floobits <RET>

only to get "Package \`json-1.2' is unavailable".  Relevant stuff in my `.emacs` is

    (load (expand-file-name "~/.emacs.d/elpa/package.el"))
    ;; http://melpa.milkbox.net/
    (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
    ;; compatibility stuff for emacs23
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
    (package-initialize)

**Comment by camdez** [comment]
@terotil Is this still an issue? `json` is not available from the package repositories because it has been built into Emacs since version 23.1 (2008). Perhaps you could run `C-h P json RET` (`describe-package`) to check which version of the `json` package you have installed?

**Comment by ggreer** [comment]
I'm pretty sure it's no longer an issue since we only support Emacs >= 24. Thanks for reminding me about this.

**Comment by camdez** [comment]
@ggreer :+1:
