### ISSUE TITLE
Cursor position and yas-snippets

### ISSUE THREAD

**Issue by wrbutros** [Floobits/floobits-emacs#85]
Having a emacs session and a web session,
When I execute a snippet in emacs (like 'for' [tab] in c-mode) the text in
both sessions differ.
The cursor position in emacs differ from the one on the web editor 
when i excecute that.

**Comment by ggreer** [comment]
Can you please specify:

* Your Emacs version.
* Your operating system.
* Any errors in \*Messages\* or \*Floobits\*

**Comment by wrbutros** [comment]
Yeah:
* GNU Emacs 24.5.1
* Arch GNU/Linux and Debian GNU/Linux
* Don't appeared any error message

When I execute a yasnippet and I press TAB many times 
(to complete snippets values), the web editor loose the emacs pointer position.
like this gif:
https://bbbscarter.files.wordpress.com/2012/09/yasnippet_anim21.gif?w=625

**Comment by wrbutros** [comment]
Is fixed... I tried in GNU Emacs 25.3
