### ISSUE TITLE
hangs when sharing a workspace on Emacs 25

### ISSUE THREAD

**Issue by aaronjensen** [Floobits/floobits-emacs#87]
When I attempt to share a public or private workspace on Emacs 25 floobits hangs Emacs and takes 100% CPU.

This is the last thing I see if I have `floobits-debug` enabled:

![https://usercontent.irccloud-cdn.com/file/0T2lajKb/*helm-mode-nil*%202016-03-19%2007-35-27.png](https://usercontent.irccloud-cdn.com/file/0T2lajKb/*helm-mode-nil*%202016-03-19%2007-35-27.png)

**Comment by ggreer** [comment]
Thanks for the bug report. Can you provide more information such as your OS & python version? Also, does Emacs 24 work for you?

**Comment by aaronjensen** [comment]
Sure thing. 

Python 2.7.11
OS X El Capitan 10.11.3

Yes, Emacs 24 works fine.

**Comment by aaronjensen** [comment]
I mentioned this in IRC, but it appears to be a conflict between floobits, Emacs 25 and helm (maybe something in the spacemacs-helm layer. If I use ivy instead of helm or the default method of getting user input for the "Create workspace owned by" prompt, it works fine.

**Comment by aaronjensen** [comment]
This is an Emacs 25 bug: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=23091
