### ISSUE TITLE
File upload fails with Python 3.5+

### ISSUE THREAD

**Issue by mkaito** [Floobits/floobits-emacs#92]
I found an issue where attempting to upload files to a workspace would get stuck in an infinite reconnection loop, constantly asking whether I would like to upload files.

The following error would show up in the floobits buffer:

    ERROR: Couldn't write to socket: The operation did not complete (write) (_ssl.c:2037)

Looking at the file in question, after figuring out that this was actually coming from the python program rather than emacs itself, showed me that this error came from raising an error called SSL_WANT_WRITE_ERROR.

Afterwards, floobits would get stuck in an infinite reconnection loop until canceled:

    ERROR: No data from sock.recv() 36 times.

Which makes sense, considering the socket was asking to have more data written before reading.

Looking into the exception name showed me that this was a new thing in python 3.5 relating to usage of non-blocking sockets. Where `send()` would previously return 0 when the socket required additional reads or writes, it now raises one of two exceptions, as detailed [here](http://code.activestate.com/lists/python-checkins/121448/).

Considering that this is new in Python 3.5, switching the interpreter to python2 works as a workaround.

**Comment by mkaito** [comment]
Python 3.6.0 (default, Jan 16 2017, 12:12:55)
		[GCC 6.3.1 20170109] on linux
		Linux hydra 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux
		GNU Emacs 25.1.1
		floobits-20170204.226

**Comment by ggreer** [comment]
OK, should be fixed in the latest release: 1.9.0.
