### ISSUE TITLE
Highlighted region not updating correctly

### ISSUE THREAD

**Issue by duncan-bayne** [Floobits/floobits-emacs#93]
I'm seeing odd errors, where the highlighted region isn't being correctly cleaned up.  After a while, the buffer winds up very hard to read:

![floobits](https://cloud.githubusercontent.com/assets/65949/24785455/4edac1e6-1b9d-11e7-8c85-d154c27fd330.png)

System details are:

```
floobits 20170204.226

FreeBSD x220 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

GNU Emacs 25.1.1
```

**Comment by ggreer** [comment]
Is this in a terminal or is it xemacs?

**Comment by Quasilyte** [comment]
Is there any way to turn highlights from collaborators off completely?
It's hard to work when buffer looks like a rainbow. 

There is also a glitch: when I type, some older highlights appear and disappear.
This is also a big distraction.

**Comment by Quasilyte** [comment]
My cursor is inside `input` string literal.
There is no real highlighting there, everyone moved their cursors in web UI away, but sometimes it still displays that area as highlighted...
I can't see what I'm actually typing in.

![image](https://user-images.githubusercontent.com/6286655/39663479-dd187344-507c-11e8-9143-33d32074a689.png)

**Comment by duncan-bayne** [comment]
@ggreer Emacs in X (StumpWM window manager).

**Comment by duncan-bayne** [comment]
@ggreer ... and in fact several of my colleagues on OSX experienced the same issue.

**Comment by duncan-bayne** [comment]
@Quasilyte no I'm afraid.  There were only two Emacs users on the team; I moved on to a different client, and the other Emacs fan is IIRC using RubyMine now, partly for this reason.

**Comment by duncan-bayne** [comment]
TBH my normal approach when I'm working with other Emacs folks is to pair in a console session w/ tmux :)  This bug is only really an issue when I'm attempting to pair remotely where the other party isn't using Emacs.

**Comment by ro6** [comment]
Any other workaround here besides constantly running `M-x floobits-clear-highlights`? @duncan-bayne What do you mean by "remove all permissions"?

**Comment by duncan-bayne** [comment]
Afraid I haven't used Floobits in years (simply because I've been managing more than coding of late); please feel free to close this issue.
