### ISSUE TITLE
urgent Floobits SSL handshake error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)  

### ISSUE THREAD

**Issue by markmark1** [Floobits/floobits-emacs#95]
Floobits SSL handshake error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

urgent not working pls let me know how to fix both in emacs and sublime and web-browser a

**Comment by kans** [comment]
@ggreer just shipped updates for all plugins that should have fixed this.  Can you confirm if it is still a problem?

**Comment by markmark1** [comment]
Yes it’s still a problem

how to update

________________________________

**Comment by markmark1** [comment]
Is there a floobits release announcement or user mailing list or slack

________________________________

**Comment by ggreer** [comment]
Updating the plugin depends on how you installed it. If you just git cloned it, you'll need to git pull and restart emacs. If you used MELPA or ELPA, you'll need to `M-x list-packages` or something similar.

**Comment by markmark1** [comment]
tried list packages - install

*Floobits SSL handshake error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:548)*

*still error*

**Comment by markus-wa** [comment]
I'm also getting this error :slightly_frowning_face: . i reinstalled everything including spacemacs, floobits, upgraded python etc..

Do you remember how this was solved @ggreer ?
