### ISSUE TITLE
emacs lisp code is all GPLv3+

### ISSUE THREAD

**Issue by fommil** [Floobits/floobits-emacs#96]
Thank you for providing your source code under the Apache 2.0! It is the best permissive license.

However, as Emacs is GPLv3+ it means that all plugins are also GPLv3 unless they are written in a subset of lisp that is independent of the lisp interpreter.

From a practical point of view, I don't think it really matters as it's not like somebody is going to take your code and run it on some proprietary fork of GNU Emacs :grinning: ... it is just a minor point about licensing that is often overlooked.

**Comment by ggreer** [comment]
I've heard this before, but I'm pretty sure that's just the FSF's favored interpretation and would never hold up in court.

Though the only way to know for sure would be if the FSF sued Floobits over this, which seems unlikely.

Thanks for the heads-up, though.
